### ISSUE TITLE
Small question regarding prompt caching

### ISSUE THREAD

**Issue by rebek43** [tbogdala/woolycore#1]
Hello, I was wondering about how exactly prompt caching works and whether or not it's possible to add additional prompt tokens to a previously set state (maybe through the prompt parameter?).
I am also unsure on how the prompt_cache_all parameter functions; does it make the prediction function output a prompt cache as part of it's return on every call?

**Comment by tbogdala** [comment]
Right now, prompt caching is a one-time operation and cannot be added to. This is something that's been on my idea list, but I haven't gotten to it yet.

The `prompt_cache_all ` in the struct `wooly_gpt_params` basically tells the `wooly_process_prompt()` to set the `prompt_cache` field of the returned structure with the prompt cache. If set to true, it will return a new prompt cache pointer on every call to `wooly_predict()`. You can pass that `prompt_cache` as the `prompt_cache_ptr` in `wooly_predict()` and needs to get free'd eventually though by calling `wooly_free_prompt_cache()`.

You can see how this is used in my unit test code [here](https://github.com/tbogdala/woolycore/blob/35aa4cb088750f10b23edbff4edb9b739d09ad41/tests/test_predictions.c#L101C1-L101C5).

---

That said, there's a different workflow shown in my [test_prediction_steps unit test](https://github.com/tbogdala/woolycore/blob/35aa4cb088750f10b23edbff4edb9b739d09ad41/tests/test_prediction_steps.c). It is all the same functionality that `wooly_predict()` wraps into one function, but its broken down into separate functions. It might be instructive to look at.

Hopefully both unit tests are commented well enough to make it easy to follow along.

--- 

Behind the scenes, the next release of woolycore will probably reimplement `wooly_predict()` in terms of these functions, as it's current implementation was a hold over from when I first made this function and essentially ported the main loop of llama.cpp's main example.

**Comment by tbogdala** [comment]
Okay, so 9138338 wiped out the old implementation of the all-in-one `wooly_predict()` function and replaced it with a loop based on the functions introduced in v0.2.0 of the library. That should make how prompt caching works more clear in all cases.

Secondly, commit 0e7909d implements the addition of `wooly_process_additional_prompt()` which allows the caller to add in some more prompt text to the context. `test_prediction_steps.c` has been modified to add additional prompt text and appears to work well.

Both are commits in the 'dev' branch, where I stage all my work before eventually pushing it to 'main', so if you want to mess with it before I get around to merging, pull that branch.

Thanks for the suggestion!
